#!/usr/bin/env python
import sundaytasks.main
import logging
import argparse
import signal
FORMAT = '%(asctime)s %(funcName)s %(levelname)-8s %(message)s'
LEVEL = logging.INFO

def signal_handler(signum, frame):
    logging.info("Received Signal: %s at frame: %s", signum, frame)

    if signum == signal.SIGTERM:
        logging.info('Received request to terminate daemon (SIGTERM)')
        main.close()
    elif signum == signal.SIGHUP:
        logging.info('Received reload config request (SIGHUP)')
        main.reload()


if __name__ == "__main__":
    signal.signal(signal.SIGHUP, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)
    description = """SundayTask runs your changes on CouchDB through a
    plugin system set up by you. It watches for changes from the schanges
    program that is tied to the same Unix socket.
    """
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('-s', '--start',
                        help='The starting point for plugins',
                        default='start')
    parser.add_argument('--socket',
                        help='The unix socket to tie to',
                        default='/tmp/stask.sock')
    parser.add_argument('-a', '--allow_design', action='store_true',
                        help='Allow design documents')
    parser.add_argument('-d', '--debug', action='store_true',
                        help='Turn on Debug')
    args = parser.parse_args()
    if args.debug:
        LEVEL = logging.DEBUG
        logging.basicConfig(format=FORMAT, level=LEVEL)
    main = sundaytasks.main.Main(args.socket, args.start, args.allow_design)
    main.start()
