#!/usr/bin/env python
import sundaytasks.main
import logging
import argparse
FORMAT = '%(asctime)s %(funcName)s %(levelname)-8s %(message)s'
LEVEL = logging.INFO

if __name__ == "__main__":
    description = """SundayTask runs your changes on CouchDB through a
    plugin system set up by you. It watches for changes from the schanges
    program that is tied to the same Unix socket.
    """
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('-s', '--start',
                         help='The starting point for plugins',
                         default='start')
    parser.add_argument('--socket',
                         help='The unix socket to tie to',
                         default='/tmp/stask.sock')
    parser.add_argument('-d', '--debug', action='store_true',
                         help='Turn on Debug')
    args = parser.parse_args()
    if args.debug:
        LEVEL = logging.DEBUG
        logging.basicConfig(format = FORMAT, level = LEVEL)
    main = sundaytasks.main.Main(args.socket, args.start)
